---
chains:
  - binary_name: wasmd
    chain_id: nois-testnet-002
    denom: unois
    faucet: "http://faucet.noislabs.com/credit"
    gas_price: 1
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-002
    prefix: nois
    rpc:
      - "http://rpc-0.noislabs.com:26657"
    wasm:
      contracts:
        - address: nois14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sch3j70
          code_id: "1"
          git_asset_name: nois_oracle
          instantiation_msg: '{"test_mode":false}'
          name: nois-oracle
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: fetchd #https://docs.fetch.ai/
    chain_id: dorado-1
    denom: atestfet
    faucet: ~ # use https://explore-dorado.fetch.ai/
    gas_price: 1000000000
    ibc_connection:
      dest: connection-0
      src: connection-12
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: dorado-1
    prefix: fetch
    rpc:
      - "https://rpc-dorado.fetch.ai:443"
    wasm:
      contracts:
        - address: fetch1e8x69y699tfm96vuc65natc4deh06yclwrapl4dwll0q5tqk36lsl2ny72
          code_id: "3242"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address: fetch1pra3jxcsx88d6dlhrvw6kfc8tchul43j6qwymsgsjg0srs79vypsnlkwut
          code_id: "3243"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: aurad
    chain_id: euphoria-1
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: connection-1
      src: connection-8
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: euphoria-1
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address: aura1ey58tn9y3gvvakfkat0qgt04v7areald7ke7d6xl8swmhppr0amq34d9gz
          code_id: "48"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address: aura1jvsewykm9kdwdt48j63ldat38pag0srq06ehj667gew3nj32nruqycq4s7
          code_id: "49"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: osmosisd
    chain_id: osmo-test-4
    denom: uosmo
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: osmo-test-4
    prefix: osmo
    rpc:
      - "https://rpc-test.osmosis.zone:443"
    wasm:
      contracts:
        - address: osmo1v8r7fpp3eddmxxq72tmumumk638mhen3ez5uzaf6fm0hr0kyvmnqndpehv
          code_id: "1484"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address: osmo1yamnygqyc72lxppgkuq4rytea3h57qx2jg57ur5k0pxll6hk72psemm0xn
          code_id: "1485"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-2
      src: connection-6
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address: stars18vjc6ysf88mpzf6tu0qpkfgt7j94z5nezclgkwlgjll8qenhg4xqz6n8xg
          code_id: "139"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address: stars10jhzj0j8vwyx0ujh3zqx2nxdfhuzzccxx9qm3exz5kvlhqanzrpqgm3knk
          code_id: "140"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: junod
    chain_id: uni-3
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi/credit"
    gas_price: 0.025
    ibc_connection:
      dest: connection-3
      src: connection-287
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: uni-3
    prefix: juno
    rpc:
      - "https://rpc.uni.juno.deuslabs.fi:443"
    wasm:
      contracts:
        - address: "null"
          code_id: "null"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address: "null"
          code_id: "null"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v2
