---
chains:
  - binary_name: wasmd
    chain_id: nois-testnet-002
    denom: unois
    faucet: "http://faucet.noislabs.com/credit"
    gas_price: 1
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-002
    prefix: nois
    rpc:
      - "http://node-0.noislabs.com:26657"
    wasm:
      contracts:
        - address: nois1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrq5z5suf
          code_id: "2"
          git_asset_name: nois_oracle
          instantiation_msg: '{"test_mode":false}'
          name: nois-oracle
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
  - binary_name: fetchd #https://docs.fetch.ai/
    chain_id: dorado-1
    denom: atestfet
    faucet: ~ # use https://explore-dorado.fetch.ai/
    gas_price: 1000000000
    ibc_connection:
      dest: connection-0
      src: connection-12
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: dorado-1
    prefix: fetch
    rpc:
      - "https://rpc-dorado.fetch.ai:443"
    wasm:
      contracts:
        - address: fetch1zkujh3jt7vgxx5hjm066x37cyzmgwgf852e74m904c5xk8l977tsmqs82u
          code_id: "3244"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
        - address: fetch1vckjrn00y2y9tujtlp6daqu70sujlfhe2w5u6zrwhass468vvsrqtcuuqt
          code_id: "3245"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
  - binary_name: aurad
    chain_id: euphoria-1
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: connection-1
      src: connection-8
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: euphoria-1
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address: aura1hgu5z4nwcxngsm9tqfwj84k8n73wfddfrvchg39lrm44zahn0fdqh2yvgd
          code_id: "51"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
        - address: aura1txv9h05z48xrgy993cruv0ljz83dp0selx5wpd0uhf5c5mtrpkgq06m6tj
          code_id: "52"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
  - binary_name: osmosisd
    chain_id: osmo-test-4
    denom: uosmo
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: ~
      src: ~
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: osmo-test-4
    prefix: osmo
    rpc:
      - "https://rpc-test.osmosis.zone:443"
    wasm:
      contracts:
        - address: osmo1qas9thwzjl2t9ttcthdwkpxpqlxk59vrtlu578qdexj6guc8a7kszzqgnr
          code_id: "1501"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
        - address: osmo1u7k3ypp3c5rumdrq30k6cl2sunls6kr4ny3ql4cvgrv207wzarkslp98s3
          code_id: "1502"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-2
      src: connection-6
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address: stars1atajhwmu769z6kp2c4htj3qxxex29rwdh55e686fm4dqc6hz80dsxeld4v
          code_id: "144"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
        - address: stars1rd8dqj0y450wu47r7ty6xkqjdpm9nyyvdnw4v7adzszd9enuq58qk257e7
          code_id: "145"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
  - binary_name: junod
    chain_id: uni-3
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi/credit"
    gas_price: 0.025
    ibc_connection:
      dest: connection-3
      src: connection-287
      counterpart:
        chain: nois-testnet-002
        contract_name: nois-oracle
    name: uni-3
    prefix: juno
    rpc:
      - "https://rpc.uni.juno.deuslabs.fi:443"
    wasm:
      contracts:
        - address: "null"
          code_id: "null"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
        - address: "null"
          code_id: "null"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.5.0
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v3
