---
chains:
  - binary_name: wasmd
    chain_id: nois-testnet-001
    denom: unois
    faucet: "http://faucet.noislabs.com/credit"
    gas_price: 1
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-001
    prefix: nois
    rpc:
      - "http://rpc-0.noislabs.com:80"
    wasm:
      contracts:
        - address:
          code_id: "1"
          git_asset_name: nois_oracle
          instantiation_msg: '{"test_mode":false}'
          name: nois-oracle
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: fetchd #https://docs.fetch.ai/
    chain_id: dorado-1
    denom: atestfet
    faucet: ~ # use https://explore-dorado.fetch.ai/
    gas_price: 1000000000
    ibc_connection:
      dest:
      src:
      counterpart:
        chain: nois-testnet-001
        contract_name: nois-oracle
    name: dorado-1
    prefix: fetch
    rpc:
      - "https://rpc-dorado.fetch.ai:443"
    wasm:
      contracts:
        - address:
          code_id: "3209"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address:
          code_id: "3210"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: aurad
    chain_id: euphoria-1
    denom: ueaura
    faucet: ~
    gas_price: 0.04
    ibc_connection:
      dest: connection-2
      src: connection-4
      counterpart:
        chain: nois-testnet-001
        contract_name: nois-oracle
    name: euphoria-1
    prefix: aura
    rpc:
      - "https://rpc.euphoria.aura.network:443"
    wasm:
      contracts:
        - address:
          code_id: "18"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address:
          code_id: "19"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
          #  - binary_name: osmosisd
          #    chain_id: osmo-test-4
          #    denom: uosmo
          #    faucet: ~
          #    gas_price: 0.04
          #    ibc_connection:
          #      dest:
          #      src:
          #      counterpart:
          #        chain: nois-testnet-001
          #        contract_name: nois-oracle
          #    name: osmo-test-4
          #    prefix: osmo
          #    rpc:
          #      - "https://rpc-test.osmosis.zone:443"
          #    wasm:
          #      contracts:
          #        - address:
          #          code_id: "1394"
          #          git_asset_name: nois_proxy
          #          instantiation_msg: "{}"
          #          name: nois-proxy
          #          url: "https://github.com/noislabs/nois-contracts"
          #          version: v0.4.1
          #        - address:
          #          code_id: "1395"
          #          git_asset_name: nois_demo
          #          instantiation_msg: defined-in-deployment-script-nois-demo
          #          name: nois-demo
          #          url: "https://github.com/noislabs/nois-contracts"
          #          version: v0.4.1
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-1
      src: connection-2
      counterpart:
        chain: nois-testnet-001
        contract_name: nois-oracle
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address:
          code_id: "135"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address:
          code_id: "136"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
  - binary_name: junod
    chain_id: uni-3
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi/credit"
    gas_price: 0.025
    ibc_connection:
      dest: connection-0
      src: connection-279
      counterpart:
        chain: nois-testnet-001
        contract_name: nois-oracle
    name: uni-3
    prefix: juno
    rpc:
      - "https://rpc.uni.juno.deuslabs.fi:443"
    wasm:
      contracts:
        - address:
          code_id: "3881"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
        - address:
          code_id: "3882"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.4.1
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v2
