---
chains:
  - binary_name: wasmd
    chain_id: nois-testnet-000
    denom: unois
    faucet: "http://faucet.noislabs.com/credit"
    gas_price: 1
    ibc_connection:
      dest: ~
      src: ~
    name: nois-testnet-000
    prefix: nois
    rpc:
      - "http://6553qqb75pb27eg2ff5lqvrpso.ingress.akash.pro:80"
    wasm:
      contracts:
        - address: nois1sdemraklrp97xgccuertrc6fq5fv7fpksggdzffqhd24nupz7p7s7q240w
          code_id: "26"
          git_asset_name: nois_oracle
          instantiation_msg: '{"test_mode":false}'
          name: nois-oracle
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.3.0
  - binary_name: starsd
    chain_id: elgafar-1
    denom: ustars
    faucet: ~
    gas_price: 0.025
    ibc_connection:
      dest: connection-11
      src: connection-0
      counterpart:
        chain: nois-testnet-000
        contract_name: nois-oracle
    name: elgafar-1
    prefix: stars
    rpc:
      - "https://rpc.elgafar-1.stargaze-apis.com:443"
    wasm:
      contracts:
        - address: stars1kshrj9hupvyfsfe0s5ucznhjg8jparxtjfm8gdmcc7at3rkw222qdeals3
          code_id: "117"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.3.0
        - address: stars16re7y6rfua2u4tz3qm6wjck6lhjzluqwheq5upxfqclu6qqcsapqjlz2m2
          code_id: "118"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.3.0
  - binary_name: junod
    chain_id: uni-3
    denom: ujunox
    faucet: "https://faucet.uni.juno.deuslabs.fi/credit"
    gas_price: 0.025
    ibc_connection:
      dest: connection-5
      src: connection-268
      counterpart:
        chain: nois-testnet-000
        contract_name: nois-oracle
    name: uni-3
    prefix: juno
    rpc:
      - "https://rpc.uni.juno.deuslabs.fi:443"
    wasm:
      contracts:
        - address: juno1empakr6y0selc5zvq48549daq4had5cqlslrxqtpj52udvv3yqysf6868a
          code_id: "3762"
          git_asset_name: nois_proxy
          instantiation_msg: "{}"
          name: nois-proxy
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.3.0
        - address: juno12hyvxlqt02erxpp3q03pzdexn4jt4tl5nrsdf7n292fhl4es5xjsq2f8d2
          code_id: "3763"
          git_asset_name: nois_demo
          instantiation_msg: defined-in-deployment-script-nois-demo
          name: nois-demo
          url: "https://github.com/noislabs/nois-contracts"
          version: v0.3.0
ibc:
  relayer:
    docker_image: noislabs/nois-relayer
  version: nois-v2
