[package]
name = "nois-protocol"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1.0", features = ["ibc3"] }
cosmwasm-schema = { version = "1.1.0" }
nois = { git = "https://github.com/noislabs/nois.git", branch = "0.5-dev" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }

[dev-dependencies]
