version: 1

chains:
  nois:
    chain_id: nois-testnet-000
    prefix: nois
    gas_price: 1unois
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.nois1uvt40rsp68wtas0y75w34qdn5h0g5eyefy5gmvzftdnupyv7q7vqg4vut2' 
    #estimated_block_time: 7000,
    #estimated_indexer_time: 250,
    faucet: http://5rh6rhqad1cgvei7qc96ia3n74.ingress.bigtractorplotting.com:80
    rpc:
      - http://6553qqb75pb27eg2ff5lqvrpso.ingress.akash.pro:80 
  uni:
    chain_id: uni-3
    prefix: juno
    gas_price: 0.025ujunox
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.juno1w9gzv42kjlj80cj3ezfmt275mh0yv70p80c7hufj8ksak82qsdkq32yzkc' #junod query wasm contract  $NOIS_PROXY_CONTRACT_ADDRESS    --node=$NODE_URL
    faucet: https://faucet.uni.juno.deuslabs.fi/credit
    rpc:
      - https://rpc.uni.juno.deuslabs.fi:443