version: 1

chains:
  TEMPLATE_RELAYER_NOIS_NAME:
    chain_id: nois-testnet-000
    prefix: nois
    gas_price: 0.1unois
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.TEMPLATE_NOIS_DRAND_CONTRACT_ADDRESS' 
    faucet: TEMPLATE_NOIS_FAUCET
    rpc:
      - TEMPLATE_NOIS_RPC
  TEMPLATE_RELAYER_CHAIN_NAME:
    chain_id: TEMPLATE_CHAIN_ID
    prefix: TEMPLATE_CHAIN_PREFIX
    gas_price: TEMPLATE_GAS_PRICESTEMPLATE_CHAIN_DENOM
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'wasm.TEMPLATE_NOIS_PROXY_CONTRACT_ADDRESS' #junod query wasm contract  $NOIS_PROXY_CONTRACT_ADDRESS    --node=$NODE_URL
    faucet: TEMPLATE_CHAIN_FAUCET_URL
    rpc:
      - TEMPLATE_CHAIN_NODE_URL