[package]
name = "nois-multitest"
version = "0.14.0"
authors = []
edition = "2021"
publish = false
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
nois-drand = { path = "../../contracts/nois-drand"}
nois-gateway = { path = "../../contracts/nois-gateway"}
nois-icecube = { path = "../../contracts/nois-icecube"}
nois-payment = { path = "../../contracts/nois-payment" }
nois-proxy = { path = "../../contracts/nois-proxy" }
nois-proxy-governance-owned = { path = "../../contracts/nois-proxy-governance-owned" }

cosmwasm-std = { version = "1.4.0", features = ["iterator", "ibc3"] }
cw-multi-test = "0.16.2"

[dev-dependencies]
