[package]
name = "nois-multitest"
version = "0.15.4"
authors = []
edition = "2021"
publish = false
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
nois-drand = { path = "../../contracts/nois-drand" }
nois-gateway = { path = "../../contracts/nois-gateway" }
nois-icecube = { path = "../../contracts/nois-icecube" }
nois-payment = { path = "../../contracts/nois-payment" }
nois-proxy = { path = "../../contracts/nois-proxy" }
nois-proxy-governance-owned = { path = "../../contracts/nois-proxy-governance-owned" }

cosmwasm-std = "2.0.4"
cw-multi-test = { version = "2.1.0-rc.1", features = ["staking", "cosmwasm_2_0"] }

[dev-dependencies]
