[package]
name = "drand-common"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1.5", features = ["iterator", "ibc3"] }

[dev-dependencies]
