[package]
name = "drand-common"
version = "0.15.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "2", features = ["iterator"] }

[dev-dependencies]
